services:
  orders-db:
    image: postgres:16.2
    container_name: orders_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data